use corupel;
INSERT INTO destinos (des_id, des_maquina)
	VALUES 
    (35, 'ACCES. CAÑERIA'),
    (18, 'ATADORA MOSCA'),
    (20, 'ATADORA TRANSPACK'),
    (38, 'AUTOELEVADORES'),
    (32, 'BOMBA ACOMY'),
    (22, 'BOOMBA ARO'),
    (34, 'BOMBAS ACERO'),
    (12, 'BOMBAS INDESUR'),
    (4, 'BULONERIA'),
    (26, 'CABEZAL B'),
    (17, 'CABEZAL WTG-006'),
    (14, 'CALDERA CALCOR'),
    (13, 'CALDERA GONELLA'),
    (39, 'CAÑERIA VAPOR'),
    (36, 'CLARK'),
    (30, 'COCEDORA AUT.'),
    (23, 'COCEDORA SEMI-AUT'),
    (37, 'COLERO COPAR'),
    (45, 'COLERO CORRUGADO'),
    (11, 'CORREAS'),
    (28, 'CORRUGADO'),
    (24, 'CUIERTAS'),
    (7, 'ELECTRICIDAD'),
    (47, 'EMPALMADOR'),
    (48, 'ENFARDADORA'),
    (43, 'ENVOLVEDORA'),
    (40, 'GUILLOTINA'),
    (19, 'IMPRESORA ISOWA'),
    (8, 'IMPRESORA LATITUD 5'),
    (41, 'IMPRESORA LATITUD 6'),
    (49, 'IMPRESORA LATITUD 7'),
    (9, 'IMPRESORA MARTIN'),
    (21, 'IMPRESORA MILKO'),
    (2, 'INSUMOS'),
    (6, 'LUBRICANTES'),
    (27, 'MANGUERA'),
    (46, 'MESA DE SALIDA'),
    (42, 'MESA DE SECADO'),
    (5, 'NEUMATICA'),
    (29, 'PARAFINADORA'),
    (44, 'PEGADORA'),
    (15, 'PINTURAS'),
    (33, 'PLANTA AFLUENTE'),
    (31, 'PROD. LIMPIEZA'),
    (25, 'SEGURIDAD E HIGIENE'),
    (1, 'SIN IDENTIFICAR'),
    (16, 'SLITTER'),
    (10, 'TINTAS '),
    (0, 'TODAS'),
    (3, 'TRANSMISIONES')    
    