INSERT INTO `proveedores` (`prov_id`,`prov_nombre`,`prov_razonsocial`,`prov_cuit`,`prov_direccion`,`prov_telefono`,`prov_telefono_dos`,`prov_contacto`,`prov_mail`), VALUES
(52 , '1001 FERRETERIA IND' , '1001 FERRETERIA IND' , '30662530480' , 'AV. 101 (RUTA 8), N� 2369 SAN MARTIN' , '011-4755-7887' , ''),
(41 , 'ABINCO SA' , 'ABINCO SA' , '' , '' , '' , ''),
(26 , 'ABIX' , 'ABIX' , '' , '' , '' , ''),
(61 , 'ACEROS VILLA BOSCH S.A' , 'ACEROS VILLA BOSCH S.A' , '' , '' , '' , ''),
(47 , 'ACOMY BOMBAS SA' , 'ACOMY BOMBAS SA' , '' , '' , '' , ''),
(121 , 'ADHESINT SRL' , 'ADHESINT SRL' , '' , '' , '' , ''),
(28 , 'ADHESIVOS INDUSTRIALES' , 'ADHESIVOS INDUSTRIALES' , '' , '' , '' , ''),
(135 , 'ADIGRA OLEOHIDRAULICA' , 'ADIGRA' , '' , 'MOSCONI 453 -L.DEL MIRADOR' , '' , ''),
(83 , 'ALEJANDRO GIRBINO' , 'ALEJANDRO GIRBINO' , '' , '' , '' , ''),
(120 , 'ALL BEARINGS  SRL' , 'ALL BEARINGS  SRL' , '' , '4 DE FEBRERO 3999' , '' , ''),
(36 , 'ALOI SANITARIOS' , 'ALOI SANITARIOS' , '' , '' , '' , ''),
(24 , 'APM' , 'APM' , '' , '' , '' , ''),
(124 , 'ARGENFLEX' , 'ARGENFLEX' , '' , '' , '' , ''),
(111 , 'ARTEMBAL S.A' , 'ARTEMBAL S.A' , '' , 'FRANCISCO BORGES 4775 - MUNRO' , ' (011),-47711179' , ''),
(84 , 'ATAPEL S.A.' , 'ATAPEL S.A.' , '' , 'PEDERNERA 1145' , ' ( 11 ), - 47552500' , ''),
(63 , 'ATESA SA' , 'ATESA SA' , '' , '' , '' , ''),
(100 , 'AUMECON' , 'AUMECON' , '' , '' , '' , ''),
(8 , 'AUTOMACION ARGENTNA' , 'AUTOMACION ARGENTNA' , '' , '' , '' , ''),
(45 , 'AUTOMAX' , 'AUTOMAX' , '' , '' , '' , ''),
(9 , 'B.A. RODAMIENTOS SRL' , 'B.A. RODAMIENTOS SRL' , '' , '' , ' ( 11 ), - 47126661' , ''),
(62 , 'BANDAX' , 'BANDAX' , '' , '' , '' , ''),
(76 , 'BENNET ANDERSON GONZALEZ & CIA' , ' GONZALEZ & CIA' , '' , 'J.S AGUERO 1817' , ' ( 11 ), - 47615007' , ''),
(97 , 'BERCAN S.R.L' , 'BERCAN S.R.L' , '' , 'AV . BELGRANO     3740' , '' , ''),
(51 , 'BULONERIA LOMA HERMOSA' , 'BULONERIA LOMA HERMOSA' , '' , '' , ' ( 90 ), - 4769-2147' , ''),
(65 , 'BUTERA' , 'BUTERA' , '' , '' , '' , ''),
(130 , 'CAHESA SA' , 'CAHESA SA' , '' , 'LA HUELLA 730 F.VARELA' , '' , ''),
(21 , 'CALZETTA NEUMATICOS S.A.' , 'CALZETTA NEUMATICOS S.A.' , '' , '' , '' , ''),
(23 , 'QUIMICA CASEROS' , 'CARABELLI' , '' , 'AV. MITRE 4405 CACEROS' , ' ( 0 ), - 4750-9220' , ''),
(82 , 'CARBOSEAL' , 'CARBOSEAL' , '' , '' , '' , ''),
(56 , 'CASA PEREZ' , 'CASA PEREZ' , '' , '' , '' , ''),
(88 , 'CEPILLOS TESEI' , 'CEPILLOS TESEI' , '' , '' , ' ( 11 ), - 46670099' , ''),
(107 , 'CHAVETAS GALAS SRL' , 'CHAVETAS GALAS SRL' , '' , '' , '' , ''),
(30 , 'CICERO' , 'CICERO' , '' , '' , '' , ''),
(6 , 'CLONSUD' , 'CLONSUD' , '' , '' , '' , ''),
(20 , 'COMERCIO DIGITAL' , 'COMERCIO DIGITAL' , '' , '' , ' ( 0 ), - 45454900' , ''),
(75 , 'CRISTIAN ALVAREZ TORNERO' , 'CRISTIAN ALVAREZ' , '' , '' , '' , ''),
(81 , 'D'ATRI' , 'D'ATRI' , '' , 'JUAN ARANGUREN 1694' , ' ( 11 ), - 46311886' , ''),
(5 , 'DECOM' , 'DECOM TECHNOLOGY CORP SA' , '' , '' , '' , ''),
(54 , 'DINATECNICA' , 'DINATECNICA' , '' , 'BLANCO ENCALADA 35 VILLA MARTELLI' , ' ( 0 ), - 47090069' , ''),
(115 , 'DISTRITEC' , 'DISTRITEC' , '' , 'AV 85 1113 -SAN MARTIN' , '' , ''),
(132 , 'DM D.MARTIN Y CIA' , 'DM D.MARTIN Y CIA' , '' , 'R. CUELLI 331' , '' , ''),
(85 , 'DONAIRE' , 'DONAIRE' , '' , '' , '' , ''),
(48 , 'DOSIVAC SA' , 'DOSIVAC SA' , '' , '' , '' , ''),
(58 , 'EL GRANERO VIVERO Y ART. LIMP' , 'EL GRANERO' , '' , '' , '' , ''),
(103 , 'ELECTRICIDAD HAEDO' , 'ELECTRICIDAD HAEDO' , '' , '' , '' , ''),
(53 , 'ELECTRICIDAD SERRANO' , 'ELECTRICIDAD SERRANO' , '' , 'AV. PEDRO DIAZ N�839 VILLA TESEI' , ' ( 0 ), - 44580081' , ''),
(101 , 'ELECTROL SRL' , 'ELECTROL SRL' , '' , 'CALLE 139 N2432 -SAN MARTIN' , '' , ''),
(69 , 'ELECTRO-OHM' , 'ELECTRO-OHM' , '' , 'AV PEDRO DIAZ 1317 HURLINGHAM' , '' , ''),
(39 , 'ELECTROSELEC' , 'ELECTROSELEC' , '' , '' , '' , ''),
(80 , 'EMAS AUTOELEVADORES SA' , 'EMAS AUTOELEVADORES SA' , '' , '' , '' , ''),
(113 , 'EMBAFLEX' , 'EMBAFLEX' , '' , '' , ' ( 0 ), - 47921828' , ''),
(127 , 'ISO-PACK' , 'EMBALAJES E INSUMOS NSDM SRL' , '' , 'MARTIN MIGUENS 7597' , ' ( 11 ), - 1535802017' , ''),
(131 , 'EMBAPACK EMBALAJE IND. Y COMERCIAL' , 'EMBAPACK' , '' , 'BERUTTI 1550 / SAN MARTIN' , '' , ''),
(73 , 'EMBRAGES SAN MARTIN' , 'EMBRAGES SAN MARTIN' , '' , '' , '' , ''),
(29 , 'FABROI' , 'FABROI' , '' , '' , '' , ''),
(12 , 'FERCOL' , 'FERCOL' , '' , '' , '' , ''),
(11 , 'FERCOR' , 'FERCOR' , '' , 'AV CAMPO DE MAYO 7806 M CORONADO' , ' ( 0 ), - 48427117' , ''),
(46 , 'FERRETODO' , 'FERRETODO' , '' , '' , '' , ''),
(117 , 'FILTRO BAHECO' , 'FILTRO BAHECO' , '' , '' , ' ( 11 ), - 47557870' , ''),
(38 , 'FORMACO' , 'FORMACO SRL' , '' , '' , '' , ''),
(15 , 'GEFINF' , 'GEFINF GENERAL INK FACTORY SA' , '' , '' , '' , ''),
(55 , 'GIORDANO SAICIF' , 'GIORDANO SAICIF' , '' , 'PTE. SARMIENTO 1201' , '' , ''),
(31 , 'GLUTAL' , 'GLUTAL' , '' , '' , '' , ''),
(114 , 'GOC SRL' , 'GOC SRL' , '' , 'ASTURIAS 5854' , '' , ''),
(125 , 'HABASIT' , 'HABASIT' , '' , 'INDALECIO GOMEZ 3951 LYNCH' , '' , ''),
(64 , 'HARDVAL S.A.' , 'HARDVAL S.A.' , '' , 'AV. SAN MARTIN (AV 85), N�1135 SAN MARTIN' , ' ( 0 ), - 4754-6766' , ''),
(40 , 'HIDRAULICA DELTA SAIC' , 'HIDRAULICA DELTA SAIC' , '' , 'AV ITALIA 335 -TIGRE' , '' , ''),
(94 , 'HIDRO-TUB' , 'HIDRO-TUB' , '' , '' , '' , ''),
(105 , 'HIERROS LA FINITA' , 'HIERROS LA FINITA' , '' , 'CORDOBA 7099' , ' ( 11 ), - 47695873' , ''),
(3 , 'INDESUR' , 'INDESUR ARGENTINA SA' , '' , 'H.ASCASUBI 480 (WILDE),' , ' ( 11 ), - 42063908/1867' , ''),
(123 , 'INDUPACK' , 'INDUPACK' , '' , '' , '' , ''),
(134 , 'INDUSELL' , 'INDUSELL' , '' , 'ATAHUALPA 5375 - TABLADA' , '' , ''),
(7 , 'INGEGRAF' , 'INGEGRAF' , '' , '' , '' , ''),
(137 , 'INSUMOS DIB' , 'INSUMOS DIB' , '' , 'SAN LORENZO 2971 - SAN ANDRES' , '' , ''),
(22 , 'ISLA GRANDE' , 'ISLA GRANDE' , '' , '' , '' , ''),
(116 , 'JOSE' , 'JOSE' , '' , '' , ' ( 15 ), - 49731767' , ''),
(37 , 'JOTA-EME MATERIALES ELECTRICOS' , 'JOTA-EME MATERIALES ELECTRICOS' , '' , '' , '' , ''),
(60 , 'LA CASA DE LOS FLEXIBLES' , 'LA CASA DE LOS FLEXIBLES' , '' , '' , '' , ''),
(90 , 'LIESA' , 'LA INDUSTRIA ELECTRICA SA' , '' , 'MONTIEL 3060 / CAP' , '' , ''),
(109 , 'LIESA LA INDUSTRIA ELECTRONICA SA' , 'LIESA LA INDUSTRIA ELECTRONICA SA' , '' , '' , '' , ''),
(43 , 'LONSUD' , 'LONSUD' , '' , 'ALFEREZ HIPOLITO BOUCHARD 2796 OLIVOS' , '' , ''),
(49 , 'LUBRICENTER CHURRUCA' , 'LUBRICENTER CHURRUCA' , '' , 'AV CHURRUCA 9950' , '' , ''),
(136 , 'MANUFACTURA MERLO' , 'MANUFACTURA MERLO' , '' , 'LAPRIDA 595 - MERLO' , '' , ''),
(119 , 'MAPAL QUIMICA' , 'MAPAL QUIMICA' , '' , 'SAN MARTIN 710' , ' ( 11 ), - 47559049' , ''),
(50 , 'MAQUITOOLS' , 'MAQUITOOLS' , '' , '' , '' , ''),
(66 , 'METALURGICA JORGE' , 'METALURGICA JORGE' , '' , 'ESTEBAN MERLO 5021' , '' , ''),
(59 , 'METALURGICA MA SRL' , 'METALURGICA MA SRL' , '' , 'PIERES 662 LINIERS' , ' ( 0 ), - 46423435' , ''),
(70 , 'MOVIMEC SA' , 'MOVIMEC SA' , '' , '' , '' , ''),
(17 , 'MULTIGOMA (TRIUNVIRATO),' , 'MULTIGOMA (TRIUNVIRATO),' , '' , '' , '' , ''),
(14 , 'NICRON GRUPO' , 'NICRON GRUPO' , '' , '' , '' , ''),
(133 , 'NOVA LATIN AMERICA' , 'NOVA LATIN AMERICA' , '' , '' , '' , ''),
(2 , 'PA.SE.T SRL' , 'PA.SE.T SRL' , '' , 'BLAS PARERA 1260' , ' ( 90 ), - 48441406/2527' , ''),
(112 , 'PABLO ERNESTO KATZ' , 'PABLO ERNESTO KATZ' , '' , 'VILLEGAS 2254 VILLA MAIPU SAN MARTIN' , '' , ''),
(99 , 'PELBA MATERIALES ELECTRICOS' , 'PELBA MATERIALES ELECTRICOS' , '' , '' , '' , ''),
(35 , 'PENTAGAS SA' , 'PENTAGAS SA' , '' , '' , '' , ''),
(67 , 'PH ELECTRONICA SA' , 'PH ELECTRONICA SA' , '' , '' , '' , ''),
(77 , 'PIEDRAS' , 'PIEDRAS' , '' , '' , '' , ''),
(27 , 'PNEUMATIC' , 'PNEUMATIC' , '' , 'LAPRIDA 4830 VILLA MARTELLI' , ' ( 0 ), - 0810-555-7638' , ''),
(93 , 'POLICENTRO SAN LUIS SA' , 'POLICENTRO SAN LUIS SA' , '' , '' , '' , ''),
(102 , 'R.TECNICA CUCHILLAS ARGENTINAS SRL' , 'R.TECNICA CUCHILLAS ARGENTINAS SRL' , '' , '' , '' , ''),
(16 , 'RAYTECNICA' , 'RAYTECNICA DON BOSCO SRL GORDILLO' , '' , '' , '' , ''),
(10 , 'RESORTES KELS' , 'RESORTES KELS' , '' , '' , '' , ''),
(122 , 'RETENES BRUCE SRL' , 'RETENES BRUCE SRL' , '' , '' , '' , ''),
(110 , 'RICH KLINGER SAACI Y F' , 'RICH KLINGER SAACI Y F' , '' , '' , '' , ''),
(34 , 'RIWO' , 'RIWO' , '' , '' , '' , ''),
(74 , 'RODASER RODAMIENTOS S.R.L' , 'RODASER RODAMIENTOS S.R.L' , '' , 'AV. RIVADAVIA 12480' , ' ( 11 ), - 46530976' , ''),
(118 , 'RODBALL SA' , 'RODBALL SA' , '' , 'CALLE 85 N1331' , ' ( 11 ), - 47550993' , ''),
(42 , 'ROMMEL TALLERES' , 'ROMMEL TALLERES' , '' , 'PERALTA RAMOS 4886 (PABLO NOGUES),' , '' , ''),
(18 , 'ROS-RODAMIENTOS SAAVEDRA' , 'ROS-RODAMIENTOS SAAVEDRA' , '' , '' , '' , ''),
(129 , 'ROTADYNE' , 'ROTADYNE ARGENTINA SA' , '' , 'CALLE 22 3067 CAP' , '' , ''),
(104 , 'SAN MARTIN REPUESTOS PARA FRENO Y EMBRAGUES' , 'SAN MARTIN REPUESTOS PARA FRENO Y EMBRAGUES' , '' , '' , '' , ''),
(108 , 'SEICO S.A' , 'SEICO S.A' , '' , 'AV SUCRE 1869 SAN ISIDRO' , ' ( 0 ), - 47197700' , ''),
(79 , 'SELLOS LAB' , 'SELLOS LAB' , '' , '' , '' , ''),
(4 , 'SERVICIO INDUSTRIAL' , 'SERVICIO INDUSTRIAL' , '' , '' , '' , ''),
(128 , 'SERYM' , 'SERYM DE MIGUEL VILLAFA�E' , '' , 'ZAPALA 4026' , '' , ''),
(25 , 'SISTEMA MANTENIC' , 'SISTEMA MANTENIC' , '' , '' , '' , ''),
(78 , 'SOLOTAPES' , 'SOLOTAPES' , '' , '' , '' , ''),
(57 , 'STM' , 'STM' , '' , '' , ' ( 0 ), - 47570504' , ''),
(106 , 'TECHNOFIT SRL' , 'TECHNOFIT SRL' , '' , '' , '' , ''),
(68 , 'TECNICA VALFELX' , 'TECNICA VALFELX' , '' , 'SAN MARTIN 755  (QUILMES),' , '' , ''),
(89 , 'TECNIVAL SA' , 'TECNIVAL SA' , '' , 'AV  101 N�895 /SAN MARTIN' , '' , ''),
(32 , 'TESSA' , 'TESSA' , '' , '' , '' , ''),
(92 , 'TODOSUNCHOS' , 'TODOSUNCHOS' , '' , 'LAMADRID 1911' , ' ( 11 ), - 48479535' , ''),
(44 , 'TORNERIA ALVAREZ' , 'TORNERIA ALVAREZ' , '' , '' , '' , ''),
(19 , 'TRAPITO' , 'TRAPITO' , '' , 'CARLOS GARDEL 439' , '' , ''),
(13 , 'TRIOPACK' , 'TRIOPACK' , '' , '' , '' , ''),
(1 , 'UNICO' , 'UNICO' , '' , 'N/D' , '' , ''),
(126 , 'VALFLEX' , 'VALFLEX' , '' , '' , '' , ''),
(72 , 'VAPOR Y AIRE ARG' , 'VAPOR Y AIRE ARG' , '' , '' , '' , ''),
(71 , 'VAPOR Y AIRE ARG' , 'VAPOR Y AIRE ARG' , '' , 'PUEYRREDON 305' , '' , ''),
(91 , 'ALVAREZ CARLOS ROBERTO' , 'VAPORTEC' , '' , 'MANUEL GARCIA 5357/ MUNRO' , '' , ''),
(98 , 'VARITEL' , 'VARITEL' , '' , 'M. BALI�A 456 LOMAS DE ZAMORA' , '' , ''),
(95 , 'WALCAN SA' , 'WALCAN SA' , '' , 'CALLE 47 - 3107' , '' , ''),
(33 , 'WISSA' , 'WISSA' , '' , '' , '' , ''),
(
